let tru = (100==100);
console.log(tru);
console.log(typeof (tru));
let sub = (100<200);
console.log(sub);
console.log(typeof(sub));
let mul =(100<99);
console.log(mul);
console.log(typeof(mul));
let div =(23==4);
console.log(div);
console.log(typeof(div));
let div1 =(1==4);
console.log(div1);
console.log(typeof(div1));
let div2 =(4==4);
console.log(div2);
console.log(typeof(div2));
let div3=(8==4);
console.log(div3);
console.log(typeof(div3));
let div4 =(66==4);
console.log(div4);
console.log(typeof(div4));
let div5 =(88<4);
console.log(div5);
console.log(typeof(div5));
let div6 =(8>4);
console.log(div6);
console.log(typeof(div6));