const frt = null;
console.log(frt);
console.log(typeof (frt));
const free = null;
console.log(free);
console.log(typeof (free));
const right = null;
console.log(right);
console.log(typeof (right));
const fast = null;
console.log(fast);
console.log(typeof (fast));
const gray = null;
console.log(gray);
console.log(typeof (gray));
const blue = null;
console.log(blue);
console.log(typeof (blue));
const black = null;
console.log(black);
console.log(typeof (black));
const grap = null;
console.log(grap);
console.log(typeof (grap));
const mag = null;
console.log(mag);
console.log(typeof (mag));
const abso = null;
console.log(abso);
console.log(typeof (abso));

