const num1 = 10;
console.log(num1);
console.log(typeof num1);
const num2 = 13;
console.log(num2);
console.log(typeof num2);
const num3 = 20;
console.log(num3);
console.log(typeof num3);
const num4 = 30;
console.log(num4);
console.log(typeof num4);
const num5 = 40;
console.log(num5);
console.log(typeof num5);
const num6 = 47;
console.log(num6);
console.log(typeof num6);
const num7 = 34;
console.log(num7);
console.log(typeof num7);
const num8 = 7;
console.log(num8);
console.log(typeof num8);
const num9 = 23;
console.log(num9);
console.log(typeof num9);
const num10 = 27;
console.log(num10);
console.log(typeof num10);