let var1 = 'hi i m shafi';
console.log(var1);
console.log(typeof(var1));
let chars = 'what up';
console.log(chars);
console.log(typeof(chars));
const char1='how are u';
console.log(char1);
console.log(typeof(char1));
const char2='programer';
console.log(char2);
console.log(typeof(char2));
let char3='modelar';
console.log(char3);
console.log(typeof(char3));
const char4='claver';
console.log(char4);
console.log(typeof(char4));
const char5='player';
console.log(char5);
console.log(typeof(char5));
let char6='singer';
console.log(char6);
console.log(typeof(char6));
let char7='designer';
console.log(char7);
console.log(typeof(char7));
