let lst;
console.log(typeof(lst));
let fals;
console.log(typeof(fals));
let tree;
console.log(typeof(tree));
let adol;
console.log(typeof(adol));
let wron;
console.log(typeof(wron));
let school;
console.log(typeof(school));
let flow;
console.log(typeof(flow));
let deg;
console.log(typeof(deg));
let deg3;
console.log(typeof(deg3));
let frog;
console.log(typeof(frog));